name: devscreening
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  avatar_glow:
  flutter_speed_dial: ^1.2.5
  provider: ^4.1.2
  tuple: ^1.0.3
  flutter_slidable: ^0.5.4
  get_it: ^4.0.2
  flutter_screenutil: ^1.1.0
  font_awesome_flutter: ^8.8.1
  flare_flutter: ^2.0.3
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/rive/checkmark.flr

  fonts:
    - family: Giroy
      fonts:
        - asset: "assets/fonts/gilroy-family/Radomir Tinkov - Gilroy-Light.otf"
          weight: 300
        - asset: "assets/fonts/gilroy-family/Radomir Tinkov - Gilroy-Regular.otf"
          weight: 400
        - asset: "assets/fonts/gilroy-family/Radomir Tinkov - Gilroy-Medium.otf"
          weight: 500
        - asset: "assets/fonts/gilroy-family/Radomir Tinkov - Gilroy-Bold.otf"
          weight: 700
